SecondCarProject/SecondCarApp/urls.py
from django.urls import path

from . import views

app_name = 'SecondCarApp'
urlpatterns = [
    path('home', views.home, name='home'),
    path('available-cars', views.available_cars, name='available-cars'),
    path('show-more/<int:id>', views.show_more, name='show-more'),
    path('predict-value/<int:id>',views.predict_value, name='predict-value'),
    path('gallery',views.gallery, name='gallery'),
    path('accuracy',views.user_accuracy, name='accuracy'),
    path('analysis',views.analysis, name='analysis'),
    path('bar-graph-1',views.bar_graph_1, name='bar-graph-1'),
    path('bar-graph-2',views.bar_graph_2, name='bar-graph-2'),
    path('pie-graph-1',views.pie_graph_1, name='pie-graph-1'),
    path('model-details',views.model_details, name='model-details'),
    path('back-to-model-btn',views.back_to_model_btn, name='back-to-model-btn'),
    path('back-to-accuracy-btn',views.back_to_accuracy_btn, name='back-to-accuracy-btn')

]

SecondCarProject/SecondCarProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('SecondCarApp.urls')),
    path('admin/', admin.site.urls),
]

SecondCarProject/templates/analysis.html
{% extends 'home.html' %}
{% block content %}
{% load static %}
<div class="row" style="margin-top: 20px;">
    <div class="col-sm-3">
        <a href="{% url 'SecondCarApp:home' %}" class="btn btn-info">Back</a>
    </div>
    <div class="col-sm-3">
        <a href="{% url 'SecondCarApp:bar-graph-1' %}" class="btn btn-info">Graph-1</a>
    </div>
    <div class="col-sm-3">
        <a href="{% url 'SecondCarApp:bar-graph-2' %}" class="btn btn-info">Graph-2</a>
    </div>
    <div class="col-sm-3">
        <a href="{% url 'SecondCarApp:pie-graph-1' %}" class="btn btn-info">Graph-3</a>
    </div>
</div>
{% if bar1_flag %}
<div class=row>
    <div class="col-sm-6">
        <center><img src="{% static 'images/bar1.png' %}" style="background-color: white;margin-top: 20px;"
                alt="image alternate" height="700" width="700"></center>
    </div>
    <div class="col-sm-2" style="background-color: white;margin-top: 20px;margin-left: 250px;height: 700;width:100;">
        <table>
            <tr>
                <th>Number</th>
                <th>Company</th>
                <th>Count</th>
            </tr>
            <tr>
                <td>0</td>
                <td>Ambassador</td>
                <td>4</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Audi</td>
                <td>60</td>
            </tr>
            <tr>
                <td>2</td>
                <td>BMW</td>
                <td>39</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Chevrolet</td>
                <td>188</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Daewoo</td>
                <td>1</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Datsun</td>
                <td>37</td>
            </tr>
            <tr>
                <td>6</td>
                <td>Fiat</td>
                <td>37</td>
            </tr>
            <tr>
                <td>7</td>
                <td>Force</td>
                <td>1</td>
            </tr>
            <tr>
                <td>8</td>
                <td>Ford</td>
                <td>238</td>
            </tr>
            <tr>
                <td>9</td>
                <td>Honda</td>
                <td>252</td>
            </tr>
            <tr>
                <td>10</td>
                <td>Hyundai</td>
                <td>821</td>
            </tr>
            <tr>
                <td>11</td>
                <td>Isuzu</td>
                <td>1</td>
            </tr>
            <tr>
                <td>12</td>
                <td>Jaguar</td>
                <td>6</td>
            </tr>
            <tr>
                <td>13</td>
                <td>Jeep</td>
                <td>3</td>
            </tr>
            <tr>
                <td>14</td>
                <td>Kia</td>
                <td>1</td>
            </tr>
            <tr>
                <td>15</td>
                <td>Land</td>
                <td>5</td>
            </tr>
            <tr>
                <td>16</td>
                <td>MG</td>
                <td>2</td>
            </tr>
            <tr>
                <td>17</td>
                <td>Mahindra</td>
                <td>365</td>
            </tr>
            <tr>
                <td>18</td>
                <td>Maruti</td>
                <td>1280</td>
            </tr>
            <tr>
                <td>19</td>
                <td>Mercedes</td>
                <td>35</td>
            </tr>
            <tr>
                <td>20</td>
                <td>Mitsubishi</td>
                <td>6</td>
            </tr>
            <tr>
                <td>21</td>
                <td>Nissan</td>
                <td>64</td>
            </tr>
            <tr>
                <td>22</td>
                <td>OpelCorsa</td>
                <td>2</td>
            </tr>
            <tr>
                <td>23</td>
                <td>Renault</td>
                <td>146</td>
            </tr>
            <tr>
                <td>24</td>
                <td>Skoda</td>
                <td>68</td>
            </tr>
            <tr>
                <td>25</td>
                <td>Tata</td>
                <td>361</td>
            </tr>
            <tr>
                <td>26</td>
                <td>Toyota</td>
                <td>206</td>
            </tr>
            <tr>
                <td>27</td>
                <td>Volkswagen</td>
                <td>107</td>
            </tr>
            <tr>
                <td>28</td>
                <td>Volvo</td>
                <td>4</td>
            </tr>
        </table>
    </div>
</div>
{% endif %}
{% if bar2_flag %}
<div class="row">
    <div class="col-sm-6">
        <center><img src="{% static 'images/bar2.png' %}" style="background-color: white;margin-top: 20px;"
                alt="image alternate" height="700" width="700"></center>
    </div>
    <div class="col-sm-2"
        style="background-color: white;margin-top: 20px;margin-left: 250px;height: 700;width:100;">
        <table>
            <tr>
                <th>Year</th>
                <th>Count</th>
            </tr>
            <tr>
                <td>1992</td>
                <td>1</td>
            </tr>
            <tr>
                <td>1995</td>
                <td>1</td>
            </tr>
            <tr>
                <td>1996</td>
                <td>2</td>
            </tr>
            <tr>
                <td>1997</td>
                <td>3</td>
            </tr>
            <tr>
                <td>1998</td>
                <td>12</td>
            </tr>
            <tr>
                <td>1999</td>
                <td>10</td>
            </tr>
            <tr>
                <td>2000</td>
                <td>12</td>
            </tr>
            <tr>
                <td>2001</td>
                <td>20</td>
            </tr>
            <tr>
                <td>2002</td>
                <td>21</td>
            </tr>
            <tr>
                <td>2003</td>
                <td>23</td>
            </tr>
            <tr>
                <td>2004</td>
                <td>42</td>
            </tr>
            <tr>
                <td>2005</td>
                <td>85</td>
            </tr>
            <tr>
                <td>2006</td>
                <td>110</td>
            </tr>
            <tr>
                <td>2007</td>
                <td>134</td>
            </tr>
            <tr>
                <td>2008</td>
                <td>145</td>
            </tr>
            <tr>
                <td>2009</td>
                <td>193</td>
            </tr>
            <tr>
                <td>2010</td>
                <td>234</td>
            </tr>
            <tr>
                <td>2011</td>
                <td>271</td>
            </tr>
            <tr>
                <td>2012</td>
                <td>415</td>
            </tr>
            <tr>
                <td>2013</td>
                <td>386</td>
            </tr>
            <tr>
                <td>2014</td>
                <td>367</td>
            </tr>
            <tr>
                <td>2015</td>
                <td>421</td>
            </tr>
            <tr>
                <td>2016</td>
                <td>357</td>
            </tr>
            <tr>
                <td>2017</td>
                <td>466</td>
            </tr>
            <tr>
                <td>2018</td>
                <td>366</td>
            </tr>
            <tr>
                <td>2019</td>
                <td>195</td>
            </tr>
            <tr>
                <td>2020</td>
                <td>48</td>
            </tr>
        </table>
    </div>
</div>
{% endif %}
{% if pie1_flag %}
<div class="row">
    <div class="col-sm-6">
        <center><img src="{% static 'images/pie1.png' %}" style="background-color: white;margin-top: 20px;"
                alt="image alternate" height="700" width="700"></center>
    </div>
    <div class="col-sm-2" style="background-color: white;margin-top: 250px;margin-left: 250px;height: 200;width:100;">
        <table title="Information about Graph">
            <tr>
                <th>Numbers</th>
                <th>Type of Fuel</th>
                <th>Percentage</th>
            </tr>
            <tr>
                <td>0</td>
                <td>CNG</td>
                <td>0.92%</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Diesel</td>
                <td>49.65%</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Electric</td>
                <td>0.02%</td>
            </tr>
            <tr>
                <td>3</td>
                <td>LPG</td>
                <td>0.53%</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Petrol</td>
                <td>48.87%</td>
            </tr>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

SecondCarProject/templates/car-details.html
{% extends 'home.html' %}
{% block content %}

<hr />
<center>
<div class="row">
    <div class="col"><a href="{% url 'SecondCarApp:home' %}" class="btn btn-info">Home</a></div>
    <div class="col"><h2 style="font-family: Quicksand; color: #5bc0de;">{{name}}</h2></div>
    <div class="col"><a href="{% url 'SecondCarApp:available-cars' %}" class="btn btn-info">Back</a></div>
</div>
</center>
<hr>
<center>
  {{year_var}}
<div class="container">
    <div class="row">

      <div class="card" style="width: 100%; height: 30%;">
        <div class="row">
            <div class="col">
                <img src="{{link}}" alt="Card image cap" height="400" width="400">
            </div>
            <div class="col m-5">
                <div class="card m-5" style="width: 70%; height: 30%;">
                    <div style="background-color: #89d6ee;">
                        <h3>Company Name : {{company_name}}</h2><hr>
                        <h4 style="color: red;">Selling Price : Rs {{selling_price}}</h4>
                        <br>
                        {% if flag %}
                        <h4 style="color: green;">Predicted Price : Rs {{predicted_value.0}}</h4>
                        {% else %}
                        <a href="{% url 'SecondCarApp:predict-value' car_id %}" class="btn btn-danger">Predict Value</a>
                        <br>
                        {% endif %}
                        <br>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
          <p class="card-text">
            <div class="row">
                <div class="col-sm-6">
                  <p >Year Of Purchase : {{year}} </p>
                </div>
                <div class="col-sm-6">
                  <p >Fuel-Type : {{fuel}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                  <p >Seller-Type : {{seller_type}}</p>
                </div>
                <div class="col-sm-6">
                  <p >Transmission : {{transmission}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                  <p > Owner-Type : {{owner}}</p>
                </div>
                <div class="col-sm-6">
                  <p >Ratings : {{Rating}}</p>
                </div>
            </div>
          </p>
          
        </div>
      </div>

    </div>
</div>
</center>
{% endblock %}

SecondCarProject/templates/home.html
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <style>
        p {
            font-family: Quicksand;
            font-weight: bolder;
            font-size: 1.5rem;
        }

        a {
            font-family: Quicksand;
            font-size: 20px;
            margin: 5 60 5 60;
            width: 40%;
        }

        body {
            background-color: black;
        }

        td {
            text-align: center;
        }
    </style>
</head>

<body>
    {% block content %}
    <center><u style="color: whitesmoke;">
            <h1 style="font-family: Quicksand; color: #0984aa;"><b>Second Car Prize Prediction</b></h1>
        </u></center>
    </center>
    <hr>
    <div class="row">

        <div class="col-sm-4">
            <center><a href="{% url 'SecondCarApp:available-cars' %}" class="btn btn-info">Used Car Segment</a></center>
        </div>
        <div class="col-sm-4">
            <center><a href="{% url 'SecondCarApp:analysis' %}"><img
                        src="https://media.istockphoto.com/photos/car-icon-cyan-blue-glossy-round-button-picture-id613335294?k=6&m=613335294&s=170667a&w=0&h=RsgXcPqYXXtI5r6wCLnekw1mIa5vX4b-2UWfvleQC24="
                        style="border-radius: 50%; height: 200; width: 200;" alt="logo" /></a><br><b
                    style="color: #0984aa;">Click for Analysis!!</b></center>
        </div>
        <div class="col-sm-4">
            <center><a href="{% url 'SecondCarApp:gallery' %}" class="btn btn-info">Gallery</a></center>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 m-5">
            <u style="color: whitesmoke;">
                <h2 style="font-family: Quicksand; color: #0984aa; padding: 2%;"><b>About Second Car</b></h2>
            </u>
            <div class="card m-4" style="width: 90%; background-color: #5bc0de;">
                <div style="font-family: Quicksand; font-size: large; padding: 5%;">
                    <b>SecondCar is India's leading car search venture that helps users buy cars that are right for
                        them. Its website and app carry rich automotive content such as expert reviews, detailed specs
                        and prices, comparisons as well as videos and pictures of all car brands and models available in
                        India. The company has tie-ups with many auto manufacturers, more than 4000 car dealers and
                        numerous financial institutions to facilitate the purchase of vehicles.
                        <br><br>SecondCar is facing issue in its used car segment. SecondCar’s board of director has
                        raised issue of customer dis-satisfaction with the car prices. Upon investigation, board has
                        found discrepancies in car prices. Prices when compared with competitors are higher by 10 – 15%.
                        Detailed review of pricing method has revealed few issues in manual vehicle inspection and
                        pricing. A bunch of vehicle pricing managers are purchasing cars from their friends at inflated
                        prices. And hence final prices have soured.
                        <br><br>Board have decided to develop a machine learning algorithm to predict the selling prices
                        of car based on historical values. As a data scientist, please suggest the best suited method
                        and model to the board.
                    </b>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-12 m-5">
            <u style="color: whitesmoke;">
                <h2 style="font-family: Quicksand; color: #0984aa; padding: 2%;"><b>Contact Us</b></h2>
            </u>
            <div class="card m-4" style="width: 90%; background-color: #5bc0de;">
                <div class="row">
                    <div class="col">
                        <div style="font-family: Quicksand; font-size: medium; padding: 5%;">
                            <b>
                                <h4>Kasim Sache</h4>
                            </b><br>
                            <b>Contact: 9113111234<br>
                                Email: itskasimsache@gmail.com</b>
                            <br>
                        </div>
                    </div>
                    <div class="col">
                        <div style="font-family: Quicksand; font-size: medium; padding: 5%;">
                            <b>
                                <h4>Sneha Kashid</h4>
                            </b><br>
                            <b>Contact: 7447615204<br>
                                Email: snehakashid1999@gmail.com</b>
                            <br>
                        </div>
                    </div>
                    <div class="col">
                        <div style="font-family: Quicksand; font-size: medium; padding: 5%;">
                            <b>
                                <h4>Vipul Bajaj</h4>
                            </b><br>
                            <b>Contact: 9131122870<br>
                                Email: vipulbajaj77@gmail.com</b>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

</body>

</html>

SecondCarProject/templates/used-cars.html
{% extends 'home.html' %}
{% block content %}
<center>
  <h1 style="font-family: Quicksand; color: #5bc0de;">Cars to Buy</h1>
</center>
<hr />
<center>
  <div class="row">
    <div class="col-sm-4"><a href="{% url 'SecondCarApp:home' %}" class="btn btn-info">Home</a></div>
    {% if not model_details_flag %}
    <div class="col-sm-4"><a href="{% url 'SecondCarApp:model-details' %}" class="btn btn-info">Model Used</a></div>
    {% else %}
    <div class="col-sm-4"
      style="font-family: Quicksand; color: #0984aa; padding: 2%; font-size: x-large; font-weight: 600;"><a href="{% url 'SecondCarApp:back-to-model-btn' %}">RANDOM FOREST
      REGRESSOR</a></div>
    {% endif %}
    {% if not accuracy %}
    <div class="col-sm-4"><a href="{% url 'SecondCarApp:accuracy' %}" class="btn btn-info">Model's Accuracy</a></div>
    {% else %}
    <div class="col-sm-4"
      style="font-family: Quicksand; color: #0984aa; padding: 2%; font-size: x-large; font-weight: 600;"><a href="{% url 'SecondCarApp:back-to-accuracy-btn' %}">{{accuracy}} %</a>
    </div>
    {% endif %}
  </div>
</center>
<hr>
<center>
  <div class="container">
    <div class="row">
      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKqu1Pa5_BwAVuENd-2_DQzcEUGv_zba9aoA&usqp=CAU"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{0.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 0 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://www.motoroids.com/wp-content/uploads/2018/01/2018-Maruti-Suzuki-Swift-India-Booking-4.jpg"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{1.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 1 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://stat.overdrive.in/wp-content/uploads/2013/05/Toyota-Etios.jpg"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{2.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 2 %}" class="btn btn-info">Show More</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://th.bing.com/th/id/OIP.6Ui0d8VVEcwwbHLN2wv6xwHaE2?pid=Api&rs=1"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{3.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 3 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://th.bing.com/th/id/OIP.NQYPHAdRxUwm8kANvLx_qQHaEl?pid=Api&rs=1"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{4.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 4 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRILew6KBPBHI1_ibndrOFq_5zXcIEPJ0uzpA&usqp=CAU"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{5.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 5 %}" class="btn btn-info">Show More</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://cdni.autocarindia.com/ExtraImages/20190408115805_INNOVA1.png"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{6.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 6 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://th.bing.com/th/id/OIP.Hwh2EJJvAtUaJoG5P9pFnwHaFj?pid=Api&rs=1"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{7.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 7 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://th.bing.com/th/id/R4d87d63503fbb659c357000f545d17c7?rik=YaJmcI%2bJ5brjzw&riu=http%3a%2f%2f1.bp.blogspot.com%2f-VTW6y00EHe0%2fUkv-P7ymr6I%2fAAAAAAAAa8I%2fTp7WlK5TzCw%2fs1600%2fSkoda-Octavia_RS_2014_20.jpg&ehk=rAl2yIfPMbxI9ojQ4WeSaxFsKozZ7nvpj3Bw%2fIXp76A%3d&risl=&pid=ImgRaw"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{8.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 8 %}" class="btn btn-info">Show More</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://di-uploads-pod2.dealerinspire.com/riverviewford2/uploads/2017/03/2017-Ford-Explorer-Ruby-Red.png"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{9.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 9 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://st.motortrend.com/uploads/sites/10/2015/11/2014-audi-q5-suv-angular-front.png" height="250px"
          alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{10.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 10 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://s.aolcdn.com/dims-global/dims3/GLOB/legacy_thumbnail/788x525/quality/85/https://s.aolcdn.com/commerce/autodata/images/USC30MBCA61A021001.jpg"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{11.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 11 %}" class="btn btn-info">Show More</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://th.bing.com/th/id/OIP.6klvVKR_Q_nEj2wWBUZcbAHaE4?pid=Api&w=2100&h=1386&rs=1" height="250px"
          alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{12.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 12 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://assets.newcars.com/images/car-pictures/original/2020-Audi-A5-Coupe-Hatchback-2.0T-Premium-2dr-All-wheel-Drive-quattro-Coupe-Photo-4.png"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{13.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 13 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://assets.newcars.com/images/car-pictures/original/2019-BMW-X5-SUV-xDrive40i-4dr-All-wheel-Drive-Sports-Activity-Vehicle-Photo-14.png"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{14.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 14 %}" class="btn btn-info">Show More</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://th.bing.com/th/id/OIP.cv-Thmm8oEfEmh1OFKHNaQHaE6?pid=Api&rs=1"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{15.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 15 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top" src="https://www.allvehiclecontracts.co.uk/Images/183788/600.jpg" height="250px"
          alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{16.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 16 %}" class="btn btn-info">Show More</a>
        </div>
      </div>

      <div class="card m-4" style="width: 20rem; height: 23rem;">
        <img class="card-img-top"
          src="https://icdn3.digitaltrends.com/image/2016-audi-rs7-performance-product-1200x630-c-ar1.91.jpg?ver=1"
          height="250px" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>{{17.name}}</b></p>
          <a href="{% url 'SecondCarApp:show-more' 17 %}" class="btn btn-info">Show More</a>
        </div>
      </div>
    </div>
  </div>
</center>
{% endblock %}